sculptool_add("age_old:sandstone_aged",
	{
		"age_old:sandstone_bricks",
		"age_old:sandstone_bricks_alt",
		"age_old:sandstone_cracked",
		"age_old:sandstone_double_slab",
		"age_old:sandstone_double_slab_alt",
		"age_old:sandstone_facade",
		"age_old:sandstone_floor",
		"age_old:sandstone_pillar",
		"age_old:sandstone_tile",
		"age_old:sandstone_wall_frieze",
		"age_old:sandstone_aged_baluster",
		"age_old:sandstone_basrelief",
		"age_old:sandstone_basrelief2",
		"age_old:sandstone_basrelief3",
	}
)

sculptool_add("age_old:stone_aged",
	{
		"age_old:stone_aged_cracked",
		"age_old:stone_aged_double_slab",
		"age_old:stone_aged_double_slab_alt",
		"age_old:stone_aged_floor",
		"age_old:stone_aged_tile",
		"age_old:stonebricks_aged",
		"age_old:stonebricks_aged_alt",
		"age_old:stone_aged_pavement",
		"age_old:stone_aged_facade",
		"age_old:stone_aged_pillar",
		"age_old:stone_basrelief",
		"age_old:stone_basrelief2",
		"age_old:stone_basrelief3",
	}
)